import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import {
  Activity,
  ArrowDownRight,
  ArrowUpRight,
  Bot,
  Cable,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  Clock3,
  Code2,
  FileText,
  FolderKanban,
  History,
  Layers3,
  ListChecks,
  Plus,
  RadioTower,
  RefreshCw,
  Settings2,
  ShieldCheck,
  Sparkles,
  TerminalSquare,
  Workflow,
} from "lucide-react";
import { FormEvent, ReactNode, useMemo, useState } from "react";

type RunStatus = "success" | "error" | "running";
type AgentStatus = "active" | "paused";
type IntegrationName = "GitHub" | "Google" | "Gemini" | "Hugging Face";
type PageTitle = { eyebrow: string; title: string; description: string; action?: ReactNode };

const formatDateTime = (value: Date | string | null | undefined) => value ? new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "—";
const formatDuration = (value: number | null | undefined) => value === null || value === undefined ? "—" : value < 1000 ? `${value}ms` : `${(value / 1000).toFixed(1)}s`;

function PageHeader({ eyebrow, title, description, action }: PageTitle) {
  return <div className="mb-8 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div>{action && <div className="shrink-0">{action}</div>}</div>;
}

function StatusBadge({ status }: { status: string }) {
  const palette: Record<string, string> = {
    success: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300",
    error: "border-rose-400/20 bg-rose-400/10 text-rose-300",
    running: "border-sky-400/20 bg-sky-400/10 text-sky-300",
    active: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300",
    paused: "border-amber-400/20 bg-amber-400/10 text-amber-300",
    connected: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300",
    granted: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300",
    limited: "border-amber-400/20 bg-amber-400/10 text-amber-300",
    not_configured: "border-slate-400/20 bg-slate-400/10 text-slate-300",
    not_granted: "border-slate-400/20 bg-slate-400/10 text-slate-300",
    unavailable: "border-rose-400/20 bg-rose-400/10 text-rose-300",
    planning: "border-violet-400/20 bg-violet-400/10 text-violet-300",
    complete: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300",
    scheduled: "border-sky-400/20 bg-sky-400/10 text-sky-300",
    event: "border-fuchsia-400/20 bg-fuchsia-400/10 text-fuchsia-300",
  };
  return <span className={cn("inline-flex items-center rounded-full border px-2.5 py-1 text-[10px] font-semibold capitalize tracking-wide", palette[status] ?? "border-border bg-muted text-muted-foreground")}>{status.replace(/_/g, " ")}</span>;
}

function MetricCard({ icon: Icon, label, value, detail, tone = "violet" }: { icon: typeof Bot; label: string; value: number; detail: string; tone?: "violet" | "cyan" | "emerald" | "amber" }) {
  const colors = { violet: "bg-violet-400/10 text-violet-300", cyan: "bg-cyan-400/10 text-cyan-300", emerald: "bg-emerald-400/10 text-emerald-300", amber: "bg-amber-400/10 text-amber-300" };
  return <section className="glass-panel group p-5"><div className="flex items-start justify-between"><div className={cn("grid h-10 w-10 place-items-center rounded-xl", colors[tone])}><Icon className="h-4.5 w-4.5" /></div><ArrowUpRight className="h-4 w-4 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" /></div><p className="mt-8 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs font-medium text-foreground">{label}</p><p className="mt-1.5 text-xs text-muted-foreground">{detail}</p></section>;
}

function EmptyState({ icon: Icon, title, detail }: { icon: typeof Bot; title: string; detail: string }) {
  return <div className="flex min-h-48 flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-card/20 px-5 py-10 text-center"><div className="grid h-10 w-10 place-items-center rounded-xl bg-muted text-muted-foreground"><Icon className="h-4 w-4" /></div><p className="mt-4 text-sm font-medium">{title}</p><p className="mt-1 max-w-sm text-xs leading-5 text-muted-foreground">{detail}</p></div>;
}

function SkeletonRows({ rows = 3 }: { rows?: number }) { return <div className="space-y-3">{Array.from({ length: rows }).map((_, index) => <div key={index} className="h-14 animate-pulse rounded-xl bg-muted/50" />)}</div>; }

function AgentTools({ agent }: { agent: { id: string; name: string; description: string; configuration: string; status: AgentStatus } }) {
  const utils = trpc.useUtils(); const update = trpc.agents.update.useMutation({ onSuccess: () => utils.agents.list.invalidate() }); const [editOpen, setEditOpen] = useState(false); const [monitorOpen, setMonitorOpen] = useState(false); const history = trpc.agents.runHistory.useQuery({ agentId: agent.id }, { enabled: monitorOpen });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); update.mutate({ id: agent.id, name: String(form.get("name")), description: String(form.get("description")), configuration: String(form.get("configuration")), status: String(form.get("status")) as AgentStatus }, { onSuccess: () => setEditOpen(false) }); };
  return <><Dialog open={editOpen} onOpenChange={setEditOpen}><DialogTrigger asChild><Button variant="outline" size="sm">Configure</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Configure {agent.name}</DialogTitle><DialogDescription>Update the agent’s purpose, current operating state, and configuration contract.</DialogDescription></DialogHeader><form className="space-y-4 pt-2" onSubmit={submit}><Input name="name" defaultValue={agent.name} required minLength={2} /><Textarea name="description" defaultValue={agent.description} required minLength={4} /><Textarea name="configuration" defaultValue={agent.configuration} /><select name="status" defaultValue={agent.status} className="field-control"><option value="active">active</option><option value="paused">paused</option></select><Button className="w-full" disabled={update.isPending}>{update.isPending ? "Saving…" : "Save agent"}</Button>{update.error && <p className="text-xs text-destructive">{update.error.message}</p>}</form></DialogContent></Dialog><Dialog open={monitorOpen} onOpenChange={setMonitorOpen}><DialogTrigger asChild><Button variant="ghost" size="sm" className="gap-1.5"><Activity className="h-3.5 w-3.5" />Monitor</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{agent.name} activity</DialogTitle><DialogDescription>Execution activity reported for this agent.</DialogDescription></DialogHeader>{history.isLoading ? <SkeletonRows rows={2} /> : history.data?.length ? <div className="max-h-80 space-y-2 overflow-auto">{history.data.map(run => <div className="rounded-xl border border-border/70 p-3" key={run.id}><div className="flex justify-between gap-3"><p className="text-xs font-medium">{run.label}</p><StatusBadge status={run.status} /></div><p className="mt-2 text-[11px] text-muted-foreground">{formatDateTime(run.startedAt)} · {formatDuration(run.durationMs)}</p></div>)}</div> : <EmptyState icon={Activity} title="No activity reported" detail="Agent runs will appear here when an authorized execution reports back to the platform." />}</DialogContent></Dialog></>;
}

function WorkflowEditor({ workflow }: { workflow: { id: string; name: string; description: string; triggerType: "scheduled" | "event"; enabled: boolean; steps: Array<{ label: string; action: string }> } }) {
  const utils = trpc.useUtils(); const update = trpc.workflows.update.useMutation({ onSuccess: () => utils.workflows.list.invalidate() }); const [open, setOpen] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const action = String(form.get("action")) as "operation" | "llm"; const configuration = action === "llm" ? JSON.stringify({ model: String(form.get("model")) }) : "{}"; const steps: Array<{ label: string; action: "operation" | "llm"; configuration: string }> = String(form.get("steps")).split("\n").map(item => item.trim()).filter(Boolean).map(label => ({ label, action, configuration })); update.mutate({ id: workflow.id, name: String(form.get("name")), description: String(form.get("description")), triggerType: String(form.get("triggerType")) as "scheduled" | "event", enabled: form.get("enabled") === "on", steps }, { onSuccess: () => setOpen(false) }); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="ghost" size="sm">Edit</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Edit {workflow.name}</DialogTitle><DialogDescription>Refine the workflow’s trigger, sequence, action type, model, and availability.</DialogDescription></DialogHeader><form className="space-y-4 pt-2" onSubmit={submit}><Input name="name" defaultValue={workflow.name} required minLength={2} /><Textarea name="description" defaultValue={workflow.description} required minLength={4} /><select name="triggerType" defaultValue={workflow.triggerType} className="field-control"><option value="scheduled">scheduled</option><option value="event">event</option></select><select name="action" defaultValue={workflow.steps[0]?.action ?? "operation"} className="field-control"><option value="operation">Deterministic operation</option><option value="llm">AI generation</option></select><select name="model" defaultValue="gpt-5-mini" className="field-control"><option value="gpt-5-mini">AstraFlow AI · gpt-5-mini</option><option value="gemini-3-flash-preview">Gemini · gemini-3-flash-preview</option></select><Textarea name="steps" defaultValue={workflow.steps.map(step => step.label).join("\n")} required /><label className="flex items-center justify-between rounded-xl border border-border/70 px-3 py-3 text-xs font-medium">Enabled<input name="enabled" type="checkbox" defaultChecked={workflow.enabled} className="h-4 w-4 accent-primary" /></label><Button className="w-full" disabled={update.isPending}>{update.isPending ? "Saving…" : "Save workflow"}</Button>{update.error && <p className="text-xs text-destructive">{update.error.message}</p>}</form></DialogContent></Dialog>;
}

function ProjectEditor({ project }: { project: { id: string; title: string; description: string; status: "planning" | "active" | "paused" | "complete"; agentIds: string[]; workflowIds: string[] } }) {
  const utils = trpc.useUtils(); const agents = trpc.agents.list.useQuery(); const workflows = trpc.workflows.list.useQuery(); const update = trpc.projects.update.useMutation({ onSuccess: () => utils.projects.list.invalidate() }); const [open, setOpen] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); update.mutate({ id: project.id, title: String(form.get("title")), description: String(form.get("description")), status: String(form.get("status")) as "planning" | "active" | "paused" | "complete", agentIds: form.getAll("agentIds").map(String), workflowIds: form.getAll("workflowIds").map(String) }, { onSuccess: () => setOpen(false) }); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="ghost" size="sm">Edit</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Edit {project.title}</DialogTitle><DialogDescription>Maintain the project’s state, description, and linked operating components.</DialogDescription></DialogHeader><form className="space-y-4 pt-2" onSubmit={submit}><Input name="title" defaultValue={project.title} required minLength={2} /><Textarea name="description" defaultValue={project.description} required minLength={4} /><select name="status" defaultValue={project.status} className="field-control"><option value="planning">planning</option><option value="active">active</option><option value="paused">paused</option><option value="complete">complete</option></select><select name="agentIds" multiple defaultValue={project.agentIds} className="field-control h-24" aria-label="Linked agents">{agents.data?.map(agent => <option value={agent.id} key={agent.id}>{agent.name}</option>)}</select><select name="workflowIds" multiple defaultValue={project.workflowIds} className="field-control h-24" aria-label="Linked workflows">{workflows.data?.map(workflow => <option value={workflow.id} key={workflow.id}>{workflow.name}</option>)}</select><Button className="w-full" disabled={update.isPending}>{update.isPending ? "Saving…" : "Save project"}</Button>{update.error && <p className="text-xs text-destructive">{update.error.message}</p>}</form></DialogContent></Dialog>;
}

export function OverviewScreen() {
  const overview = trpc.operations.overview.useQuery();
  const data = overview.data;
  return <>
    <PageHeader eyebrow="Command center" title="System, at a glance." description="A quiet, live picture of the components that power your AI operations." action={<Button variant="outline" onClick={() => overview.refetch()} className="gap-2"><RefreshCw className="h-3.5 w-3.5" />Refresh view</Button>} />
    {overview.isLoading ? <SkeletonRows rows={4} /> : <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={Bot} label="Active agents" value={data?.activeAgents ?? 0} detail={`${data?.totalAgents ?? 0} configured in workspace`} /><MetricCard icon={Workflow} label="Enabled workflows" value={data?.enabledWorkflows ?? 0} detail={`${data?.totalWorkflows ?? 0} total orchestration flows`} tone="cyan" /><MetricCard icon={Cable} label="Connected integrations" value={data?.connectedIntegrations ?? 0} detail={`${data?.totalIntegrations ?? 0} services in the catalog`} tone="emerald" /><MetricCard icon={Clock3} label="Scheduled jobs" value={data?.enabledScheduledJobs ?? 0} detail="Ready for recurring execution" tone="amber" /></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.85fr]">
        <section className="glass-panel overflow-hidden"><div className="flex items-center justify-between border-b border-border/70 px-5 py-4"><div><p className="text-sm font-semibold">Recent workflow runs</p><p className="mt-0.5 text-xs text-muted-foreground">Latest execution activity across this workspace</p></div><History className="h-4 w-4 text-muted-foreground" /></div>{data?.recentRuns?.length ? <div className="divide-y divide-border/60">{data.recentRuns.map(run => <div key={run.id} className="flex items-center gap-3 px-5 py-4"><div className="grid h-8 w-8 place-items-center rounded-lg bg-muted"><TerminalSquare className="h-3.5 w-3.5 text-muted-foreground" /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{run.label}</p><p className="mt-1 text-[11px] text-muted-foreground">{formatDateTime(run.startedAt)} · {formatDuration(run.durationMs)}</p></div><StatusBadge status={run.status} /></div>)}</div> : <EmptyState icon={History} title="No runs recorded" detail="Execution history will appear here when an agent, workflow, or recurring job reports activity." />}</section>
        <section className="glass-panel overflow-hidden"><div className="border-b border-border/70 px-5 py-4"><p className="text-sm font-semibold">Integration health</p><p className="mt-0.5 text-xs text-muted-foreground">Authentication and permission signals</p></div><div className="divide-y divide-border/60">{data?.integrations?.map(integration => <div key={integration.id} className="flex items-center gap-3 px-5 py-3.5"><div className={cn("h-2 w-2 rounded-full", integration.authState === "connected" ? "bg-emerald-400 shadow-[0_0_10px_currentColor] text-emerald-400" : "bg-slate-500")} /><p className="flex-1 text-xs font-medium">{integration.name}</p><StatusBadge status={integration.authState} /></div>)}</div></section>
      </div>
    </>}
  </>;
}

export function AgentsScreen() {
  const utils = trpc.useUtils();
  const agents = trpc.agents.list.useQuery();
  const create = trpc.agents.create.useMutation({ onSuccess: () => utils.agents.list.invalidate() });
  const setStatus = trpc.agents.setStatus.useMutation({ onSuccess: () => utils.agents.list.invalidate() });
  const [open, setOpen] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ name: String(form.get("name")), description: String(form.get("description")), configuration: String(form.get("configuration") || "{}") }, { onSuccess: () => setOpen(false) }); };
  return <><PageHeader eyebrow="Intelligence layer" title="AI agents" description="Create and monitor the focused operators that execute work across your platform." action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="gap-2"><Plus className="h-4 w-4" />New agent</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create an AI agent</DialogTitle><DialogDescription>Define a clear responsibility and a compact configuration contract.</DialogDescription></DialogHeader><form className="space-y-4 pt-2" onSubmit={submit}><Input name="name" required minLength={2} placeholder="Agent name" /><Textarea name="description" required minLength={4} placeholder="What should this agent own?" /><Textarea name="configuration" placeholder='Configuration JSON, e.g. {"mode":"research"}' /><Button className="w-full" disabled={create.isPending}>{create.isPending ? "Creating…" : "Create agent"}</Button>{create.error && <p className="text-xs text-destructive">{create.error.message}</p>}</form></DialogContent></Dialog>} />
    {agents.isLoading ? <SkeletonRows /> : agents.data?.length ? <div className="grid gap-4 lg:grid-cols-2">{agents.data.map(agent => <section className="glass-panel p-5" key={agent.id}><div className="flex justify-between gap-4"><div className="flex min-w-0 gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-400/10 text-violet-300"><Bot className="h-4 w-4" /></div><div className="min-w-0"><p className="truncate text-sm font-semibold">{agent.name}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{agent.description}</p></div></div><StatusBadge status={agent.status} /></div><div className="mt-5 flex items-center justify-between border-t border-border/60 pt-4"><p className="text-[11px] text-muted-foreground">Updated {formatDateTime(agent.updatedAt)}</p><div className="flex items-center gap-1"><AgentTools agent={agent} /><Switch checked={agent.status === "active"} onCheckedChange={checked => setStatus.mutate({ id: agent.id, status: checked ? "active" : "paused" })} disabled={setStatus.isPending} /></div></div></section>)}</div> : <EmptyState icon={Bot} title="Start with your first agent" detail="Create a specialized agent for research, coding, content, triage, or any repeatable responsibility." />}</>;
}

export function WorkflowsScreen() {
  const utils = trpc.useUtils();
  const workflows = trpc.workflows.list.useQuery();
  const create = trpc.workflows.create.useMutation({ onSuccess: () => utils.workflows.list.invalidate() });
  const setEnabled = trpc.workflows.setEnabled.useMutation({ onSuccess: () => utils.workflows.list.invalidate() }); const runNow = trpc.workflows.runNow.useMutation({ onSuccess: () => { utils.workflows.runHistory.invalidate(); utils.operations.overview.invalidate(); utils.operations.runs.invalidate(); } });
  const [open, setOpen] = useState(false); const [historyId, setHistoryId] = useState<string | null>(null);
  const history = trpc.workflows.runHistory.useQuery({ workflowId: historyId ?? "unselected" }, { enabled: Boolean(historyId) });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const rawSteps = String(form.get("steps")).split("\n").map(line => line.trim()).filter(Boolean); const action = String(form.get("action")) as "operation" | "llm"; const configuration = action === "llm" ? JSON.stringify({ model: String(form.get("model")) }) : "{}"; create.mutate({ name: String(form.get("name")), description: String(form.get("description")), triggerType: String(form.get("triggerType")) as "scheduled" | "event", steps: rawSteps.map(label => ({ label, action, configuration })) }, { onSuccess: () => setOpen(false) }); };
  return <><PageHeader eyebrow="Orchestration layer" title="Workflows" description="Compose repeatable sequences, choose their trigger type, and watch their run history." action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="gap-2"><Plus className="h-4 w-4" />New workflow</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create a workflow</DialogTitle><DialogDescription>Steps are ordered from top to bottom. AI actions use the project’s built-in AI service and consume project credits only when run.</DialogDescription></DialogHeader><form className="space-y-4 pt-2" onSubmit={submit}><Input name="name" required minLength={2} placeholder="Workflow name" /><Textarea name="description" required minLength={4} placeholder="Describe the desired outcome" /><select name="triggerType" defaultValue="scheduled" className="field-control"><option value="scheduled">scheduled</option><option value="event">event</option></select><select name="action" defaultValue="operation" className="field-control"><option value="operation">Deterministic operation</option><option value="llm">AI generation</option></select><select name="model" defaultValue="gpt-5-mini" className="field-control"><option value="gpt-5-mini">AstraFlow AI · gpt-5-mini</option><option value="gemini-3-flash-preview">Gemini · gemini-3-flash-preview</option></select><Textarea name="steps" required placeholder={"Collect inputs\nAnalyze context\nDeliver result"} /><Button className="w-full" disabled={create.isPending}>{create.isPending ? "Creating…" : "Create workflow"}</Button>{create.error && <p className="text-xs text-destructive">{create.error.message}</p>}</form></DialogContent></Dialog>} />
    {workflows.isLoading ? <SkeletonRows /> : workflows.data?.length ? <div className="space-y-4">{workflows.data.map(workflow => <section className="glass-panel p-5" key={workflow.id}><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div className="flex min-w-0 gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><Workflow className="h-4 w-4" /></div><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{workflow.name}</p><StatusBadge status={workflow.triggerType} /><StatusBadge status={workflow.enabled ? "active" : "paused"} /></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{workflow.description}</p></div></div><div className="flex flex-wrap items-center gap-1"><WorkflowEditor workflow={workflow} /><Button variant="default" size="sm" disabled={runNow.isPending || !workflow.enabled} onClick={() => runNow.mutate({ workflowId: workflow.id })} className="gap-1.5"><Sparkles className="h-3.5 w-3.5" />{runNow.isPending ? "Running…" : "Run now"}</Button><Button variant="outline" size="sm" onClick={() => setHistoryId(workflow.id)} className="gap-1.5"><History className="h-3.5 w-3.5" />History</Button><Switch checked={workflow.enabled} onCheckedChange={enabled => setEnabled.mutate({ id: workflow.id, enabled })} /></div></div><div className="mt-5 grid gap-2 border-t border-border/60 pt-4 sm:grid-cols-3">{workflow.steps.length ? workflow.steps.map((step, index) => <div key={step.id} className="rounded-lg border border-border/60 bg-muted/35 px-3 py-2.5"><p className="text-[10px] font-semibold uppercase tracking-wider text-primary">Step {index + 1} · {step.action}</p><p className="mt-1 truncate text-xs font-medium">{step.label}</p></div>) : <p className="text-xs text-muted-foreground">No steps have been defined.</p>}</div></section>)}</div> : <EmptyState icon={Workflow} title="No workflows yet" detail="Create your first sequence with a scheduled or event trigger and a clear list of operational steps." />}
    <Dialog open={Boolean(historyId)} onOpenChange={openState => !openState && setHistoryId(null)}><DialogContent><DialogHeader><DialogTitle>Workflow run history</DialogTitle><DialogDescription>Latest execution records for the selected workflow.</DialogDescription></DialogHeader>{history.isLoading ? <SkeletonRows rows={2} /> : history.data?.length ? <div className="max-h-80 space-y-2 overflow-auto">{history.data.map(run => <div key={run.id} className="rounded-xl border border-border/70 p-3"><div className="flex justify-between gap-3"><p className="text-xs font-medium">{run.label}</p><StatusBadge status={run.status} /></div><p className="mt-2 text-[11px] text-muted-foreground">{formatDateTime(run.startedAt)} · {formatDuration(run.durationMs)}</p></div>)}</div> : <EmptyState icon={History} title="No run history" detail="This workflow has not reported an execution yet." />}</DialogContent></Dialog>
  </>;
}

export function ProjectsScreen() {
  const utils = trpc.useUtils(); const projects = trpc.projects.list.useQuery(); const agents = trpc.agents.list.useQuery(); const workflows = trpc.workflows.list.useQuery(); const create = trpc.projects.create.useMutation({ onSuccess: () => utils.projects.list.invalidate() }); const [open, setOpen] = useState(false);
  const getSelected = (form: FormData, field: string) => form.getAll(field).map(String);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ title: String(form.get("title")), description: String(form.get("description")), status: String(form.get("status")) as "planning" | "active" | "paused" | "complete", agentIds: getSelected(form, "agentIds"), workflowIds: getSelected(form, "workflowIds") }, { onSuccess: () => setOpen(false) }); };
  return <><PageHeader eyebrow="Portfolio layer" title="Projects" description="Keep goals, connected agents, and workflow dependencies together in a single operating record." action={<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="gap-2"><Plus className="h-4 w-4" />New project</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create a project</DialogTitle><DialogDescription>Link the operators and workflows responsible for delivery.</DialogDescription></DialogHeader><form className="space-y-4 pt-2" onSubmit={submit}><Input name="title" required minLength={2} placeholder="Project title" /><Textarea name="description" required minLength={4} placeholder="Project context and intended outcome" /><select name="status" defaultValue="planning" className="field-control"><option value="planning">planning</option><option value="active">active</option><option value="paused">paused</option><option value="complete">complete</option></select><select name="agentIds" multiple className="field-control h-24" aria-label="Linked agents">{agents.data?.map(agent => <option key={agent.id} value={agent.id}>{agent.name}</option>)}</select><select name="workflowIds" multiple className="field-control h-24" aria-label="Linked workflows">{workflows.data?.map(workflow => <option key={workflow.id} value={workflow.id}>{workflow.name}</option>)}</select><p className="text-[11px] text-muted-foreground">Use Ctrl/Cmd to choose multiple links.</p><Button className="w-full" disabled={create.isPending}>{create.isPending ? "Creating…" : "Create project"}</Button>{create.error && <p className="text-xs text-destructive">{create.error.message}</p>}</form></DialogContent></Dialog>} />
    {projects.isLoading ? <SkeletonRows /> : projects.data?.length ? <div className="grid gap-4 lg:grid-cols-2">{projects.data.map(project => <section className="glass-panel p-5" key={project.id}><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold">{project.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{project.description}</p></div><div className="flex items-center gap-1"><StatusBadge status={project.status} /><ProjectEditor project={project} /></div></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-border/60 pt-4"><div className="rounded-lg bg-muted/45 px-3 py-2"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Linked agents</p><p className="mt-1 text-sm font-semibold">{project.agentIds.length}</p></div><div className="rounded-lg bg-muted/45 px-3 py-2"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Linked workflows</p><p className="mt-1 text-sm font-semibold">{project.workflowIds.length}</p></div></div></section>)}</div> : <EmptyState icon={FolderKanban} title="No projects are tracked" detail="Bring agents and automation work together under the goals they support." />}</>;
}

export function IntegrationsScreen() {
  const integrations = trpc.integrations.list.useQuery();
  return <><PageHeader eyebrow="Connection layer" title="Integrations health" description="Current health reflects only authorized project connections; services remain explicitly unconfigured until a real connector is enabled." />{integrations.isLoading ? <SkeletonRows rows={4} /> : <div className="grid gap-4 xl:grid-cols-2">{integrations.data?.map(integration => <section className="glass-panel p-5" key={integration.id}><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Cable className="h-4 w-4" /></div><div><p className="text-sm font-semibold">{integration.name}</p><p className="mt-1 text-xs text-muted-foreground">{integration.authState === "not_configured" ? "No authorized connector is configured" : `Last checked ${formatDateTime(integration.lastCheckedAt)}`}</p></div></div><StatusBadge status={integration.authState} /></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-border/60 pt-4"><div><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Authentication</p><div className="mt-1"><StatusBadge status={integration.authState} /></div></div><div><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Permissions</p><div className="mt-1"><StatusBadge status={integration.permissionState} /></div></div></div><div className="mt-4 rounded-xl border border-border/60 bg-muted/30 p-3 text-[11px] leading-5 text-muted-foreground">Connection state is derived only from authorized configuration. Raw API keys and account credentials are never requested in this interface.</div></section>)}</div>}</>;
}

export function RunsScreen() {
  const [page, setPage] = useState(1); const runs = trpc.operations.runs.useQuery({ page, pageSize: 8 }); const totalPages = Math.max(1, Math.ceil((runs.data?.total ?? 0) / 8));
  return <><PageHeader eyebrow="Observability layer" title="Execution logs" description="A paginated record of the runs that move work through your system, with status, duration, and output." />
    <section className="glass-panel overflow-hidden">{runs.isLoading ? <div className="p-5"><SkeletonRows rows={5} /></div> : runs.data?.items.length ? <><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-border/70 bg-muted/20 text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground"><tr><th className="px-5 py-3">Run</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Started</th><th className="px-5 py-3">Duration</th><th className="px-5 py-3">Log output</th></tr></thead><tbody className="divide-y divide-border/60">{runs.data.items.map(run => <tr key={run.id} className="align-top text-xs"><td className="px-5 py-4"><p className="font-medium">{run.label}</p><p className="mt-1 capitalize text-muted-foreground">{run.sourceType.replace("_", " ")}</p></td><td className="px-5 py-4"><StatusBadge status={run.status as RunStatus} /></td><td className="whitespace-nowrap px-5 py-4 text-muted-foreground">{formatDateTime(run.startedAt)}</td><td className="whitespace-nowrap px-5 py-4 text-muted-foreground">{formatDuration(run.durationMs)}</td><td className="max-w-sm px-5 py-4 text-muted-foreground"><p className="line-clamp-2 leading-5">{run.logOutput || "No log output recorded."}</p></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-border/70 px-5 py-3"><p className="text-xs text-muted-foreground">Page {page} of {totalPages} · {runs.data.total} runs</p><div className="flex gap-2"><Button variant="outline" size="icon" disabled={page <= 1} onClick={() => setPage(value => value - 1)}><ChevronLeft className="h-4 w-4" /></Button><Button variant="outline" size="icon" disabled={page >= totalPages} onClick={() => setPage(value => value + 1)}><ChevronRight className="h-4 w-4" /></Button></div></div></> : <div className="p-5"><EmptyState icon={ListChecks} title="No execution logs yet" detail="Runs are added when agents, workflows, or scheduled jobs report activity." /></div>}</section></>;
}

export function SchedulesScreen() {
  const utils = trpc.useUtils(); const schedules = trpc.schedules.list.useQuery(); const workflows = trpc.workflows.list.useQuery(); const create = trpc.schedules.create.useMutation({ onSuccess: () => utils.schedules.list.invalidate() }); const toggle = trpc.schedules.setEnabled.useMutation({ onSuccess: () => utils.schedules.list.invalidate() }); const [open, setOpen] = useState(false); const isPreview = import.meta.env.DEV;
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const workflowId = String(form.get("workflowId") || ""); create.mutate({ name: String(form.get("name")), workflowId, cronExpression: String(form.get("cronExpression")) }, { onSuccess: () => setOpen(false) }); };
  return <><PageHeader eyebrow="Continuity layer" title="Scheduled jobs" description="Create recurring background work with six-field UTC cron expressions and managed lifecycle controls." action={<div className="text-right"><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button disabled={isPreview} className="gap-2"><Plus className="h-4 w-4" />{isPreview ? "Publish to enable jobs" : "New scheduled job"}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create a scheduled job</DialogTitle><DialogDescription>Jobs begin operating after this site is published, so platform callbacks have a stable endpoint.</DialogDescription></DialogHeader><form className="space-y-4 pt-2" onSubmit={submit}><Input name="name" minLength={2} required placeholder="Job name" /><select name="workflowId" className="field-control" required defaultValue=""><option value="" disabled>Select a workflow</option>{workflows.data?.map(workflow => <option key={workflow.id} value={workflow.id}>{workflow.name}</option>)}</select><Input name="cronExpression" required placeholder="0 0 9 * * *" /><p className="text-[11px] leading-5 text-muted-foreground">Use seconds, minutes, hours, day-of-month, month, day-of-week in UTC. Minimum interval: 60 seconds.</p><Button className="w-full" disabled={create.isPending}>{create.isPending ? "Creating…" : "Create scheduled job"}</Button>{create.error && <p className="text-xs text-destructive">{create.error.message}</p>}</form></DialogContent></Dialog>{isPreview && <p className="mt-1.5 text-[10px] text-muted-foreground">Publishing unlocks managed recurring jobs.</p>}</div>} />
    {schedules.isLoading ? <SkeletonRows /> : schedules.data?.length ? <div className="space-y-3">{schedules.data.map(job => <section className="glass-panel flex flex-col gap-4 p-5 md:flex-row md:items-center" key={job.id}><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-400/10 text-amber-300"><Clock3 className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{job.name}</p><StatusBadge status={job.enabled ? "active" : "paused"} /></div><p className="mt-1 font-mono text-xs text-muted-foreground">{job.cronExpression}</p></div><div className="grid grid-cols-2 gap-x-6 gap-y-1 text-xs"><div><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Last run</p><p className="mt-1">{formatDateTime(job.lastRunAt)}</p></div><div><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Next run</p><p className="mt-1">{formatDateTime(job.nextRunAt)}</p></div></div><div className="flex items-center gap-2"><span className="text-xs text-muted-foreground">{job.enabled ? "Enabled" : "Paused"}</span><Switch checked={job.enabled} onCheckedChange={enabled => toggle.mutate({ id: job.id, enabled })} disabled={toggle.isPending} /></div></section>)}</div> : <EmptyState icon={Clock3} title="No scheduled jobs" detail="Create a recurring schedule for a workflow once the platform is published." />}</>;
}

export function SettingsScreen() {
  const { data: profile } = trpc.auth.me.useQuery();
  const integrations = trpc.integrations.list.useQuery();
  const connected = useMemo(() => integrations.data?.filter(item => item.authState === "connected").length ?? 0, [integrations.data]);
  return <><PageHeader eyebrow="Control layer" title="Settings" description="A focused configuration view for your workspace profile and external service connection posture." /><div className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><section className="glass-panel p-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary"><Settings2 className="h-4 w-4" /></div><div><p className="text-sm font-semibold">Workspace profile</p><p className="mt-1 text-xs text-muted-foreground">Identity from your authenticated session</p></div></div><div className="mt-6 space-y-3"><div className="rounded-xl bg-muted/35 px-4 py-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Name</p><p className="mt-1 text-sm font-medium">{profile?.name || "Workspace user"}</p></div><div className="rounded-xl bg-muted/35 px-4 py-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Email</p><p className="mt-1 text-sm font-medium">{profile?.email || "Not shared"}</p></div><div className="rounded-xl bg-muted/35 px-4 py-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Access role</p><p className="mt-1 text-sm font-medium capitalize">{profile?.role || "user"}</p></div></div></section><section className="glass-panel p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold">External connection posture</p><p className="mt-1 max-w-xl text-xs leading-5 text-muted-foreground">This workspace displays only authorized connector status. Secret values remain outside the interface and are never retrievable.</p></div><div className="rounded-xl bg-primary/10 px-3 py-2 text-right"><p className="text-lg font-semibold text-primary">{connected}</p><p className="text-[10px] uppercase tracking-wider text-primary/80">Connected</p></div></div><div className="mt-6 divide-y divide-border/60">{integrations.data?.map(item => <div className="flex items-center justify-between gap-3 py-3" key={item.id}><div className="flex items-center gap-3"><ShieldCheck className={cn("h-4 w-4", item.authState === "connected" ? "text-emerald-400" : "text-muted-foreground")} /><div><p className="text-xs font-medium">{item.name}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{item.authState === "connected" ? "Authorized connector detected" : "No authorized connector configured"}</p></div></div><StatusBadge status={item.permissionState} /></div>)}</div><div className="mt-5 flex gap-2 rounded-xl border border-primary/15 bg-primary/5 p-3 text-xs leading-5 text-primary/90"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0" />To connect a live provider, use the platform’s protected project connection settings. This application intentionally never accepts or exposes raw credentials.</div></section></div></>;
}
